function captura() {
    var nombre=document.getElementById("nomest").value;
    var apellido=document.getElementById("apell").value;
    var pais=document.getElementById("pais").value;
    var email=document.getElementById("email").value;
    var genero=document.getElementById("genero").value;
    var naci=document.getElementById("nacimiento").value;
    var paisres=document.getElementById("paisres").value;
    var depares=document.getElementById("depares").value;
    var telcasa=document.getElementById("telcasa").value;
    var telcel=document.getElementById("telcelular").value;
    var domici=document.getElementById("domicilio").value;

    var str="";
    str += "<article>";
    str += "<table class=\"tab-x\" summary=\"Registro\">";
    str += "<thead>";
    str += "<tr><th>Datos</th><th>Resultados</th></tr>";
    str += "</thead>";
    str += "<tbody>";
    str += "<tr>";
    str += "<td>" + "Nombre" + " </td><td> " + nombre + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "Apellido" + " </td><td> " + apellido + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "País de nacimiento" + " </td><td> " + pais + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "email" + " </td><td> " + email + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "genero" + " </td><td> " + genero + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "Fecha de nacimiento" + " </td><td> " + naci + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "País de residencia" + " </td><td> " + paisres + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "Departamentos" + " </td><td> " + depares + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "telefono-casa" + " </td><td> " + telcasa + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "telefono-celular" + " </td><td> " + telcel + "</td>"; 
    str += "</tr>";
    str += "<tr>";
    str += "<td>" + "Domicilio" + " </td><td> " + domici + "</td>"; 
    str += "</tr>";
    str += "</tbody>";
    str + "</table>";
    str += "</article>";

    document.write(str);    
} 
